# Generated by Django 5.2.1 on 2025-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preface', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=255, null=True)),
                ('created_by', models.IntegerField(default='', max_length=11, null=True)),
                ('created_at', models.DateTimeField(default='', null=True)),
                ('updated_by', models.IntegerField(default='', max_length=11, null=True)),
                ('updated_at', models.DateTimeField(default='', null=True)),
            ],
        ),
    ]
